env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "tJlx0mV5/Eemy0ZYpsaG3VnK3Zjuh410QTrKC5PNp2SjFA3nBM1StqTuu/Ua2vL7N8HLlJk2AtrmomiYXbmlZpCHx0Ohn23C3XwaaoLFnOrnOhpYJfgsjr2aCLWyLe29YIU41qkJSQQSW5ipSZyEGZCeW2Pf6C/Ep2UerbxEH//UgUAcxKUblCx71O1JZxsod7Df/lsr1lbCWf3XXeZUCD7dWU1kJzJWwEZYvBQp3YsJbDwQZHD6ZYW95KH6ClDFW3SbkNCK/1mBr+X80ECKmb/jCjy4MOfMydnLD3c9fPwJcy6W4Xzx58LdbAsnInWhLy1jytWT7zM7LzXS6rTKlZGFfV3i3SuWX9aR9llXraPiYpPafT1VMv1T32pgf42ljr7s+1kmHs008N8cCyF+7Kj7W4RfgYoZFlIAdwbtGxUZwaUoDqVzj4H0PNKKkEA/plAx5cv2E5m5uiGQkwHstPZtoH5osERkdxuJJJsVN6ux/PWEpNcNh/jCR9QgfKpMVKSYoSjvLADwicscjHLQqocJoOjg7GPFVyLpMprkx4XQ97RL9nBsMhQfwZi4xgJwK3c+Po8qz9JbHZv2g9Og/6tizOqNyWIm3hncVsAWbgul5vToCrQWDiUhvT/ZAUScTMf9um/U7v2OjTdkc8W9VFL2cvLPQx1mOHIDnokihL0="

language: c

os:
    - linux

dist: trusty
sudo: required

branches:
    only:
        - coverity-scan

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:441 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - wget -c http://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - tar xf gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - export PATH=$PATH:$PWD/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/bin/
    - aarch64-linux-gnu-gcc --version
    # exporting the variable to be used by make utility
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export NUMCPUS=`nproc`
    - export XEN_TARGET_ARCH=arm64

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
        packages:
            - zlib1g-dev
            - libncurses5-dev
            - libssl-dev
            - python2.7-dev
            - xorg-dev
            - uuid-dev
            - libyajl-dev
            - libaio-dev
            - libglib2.0-dev
            - libpixman-1-dev
            - pkg-config
            - flex
            - bison
            - gettext
            - acpica-tools
            - bin86
            - bcc
            - libc6-dev-i386
            - libnl-3-dev
            - ocaml-nox
            - libfindlib-ocaml-dev
            - transfig
            - pandoc
            - gcc-arm-linux-gnueabihf
            - gcc-aarch64-linux-gnu
            - gcc-5
            - g++-5
            - clang-3.8
    coverity_scan:
        project:
            name: "xen-troops/xen"
            description: "Build submitted via Travis CI"
        notification_email: joculator@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler aarch64-linux-gnu-gcc --template"
        build_command: "make xen -j$NUMCPUS XEN_TARGET_ARCH=$XEN_TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE XSM_ENABLE=y CONFIG_HAS_SCIF=y CONFIG_DEBUG=y CONFIG_EARLY_PRINTK=salvator CONFIG_QEMU_XEN=n"
        branch_pattern: coverity-scan

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make xen -j$NUMCPUS XEN_TARGET_ARCH=$XEN_TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE XSM_ENABLE=y CONFIG_HAS_SCIF=y CONFIG_DEBUG=y CONFIG_EARLY_PRINTK=salvator CONFIG_QEMU_XEN=n; fi
